import { expect, test } from "@playwright/test";

test("demo project can compare, resume, and show ranked results", async ({ page }) => {
  await page.goto("/");
  await page.locator("html[data-resorter-ready='true']").waitFor();
  await page.getByRole("button", { name: "先用演示数据体验" }).click();
  await expect(page.getByRole("heading", { name: /demo 的已评分收藏/ })).toBeVisible();
  await expect(page.getByText(/重点比较同分作品和相邻分档/)).toBeVisible();
  await page.getByRole("button", { name: /开始快速比较 · 建议 16 次/ }).click();
  await expect(page.getByRole("heading", { name: "哪一部更值得你给出高分？" })).toBeVisible();
  await expect(page.getByText(/原评分 \d/)).toHaveCount(0);
  const originalPair = await page.locator(".media-card h2").allTextContents();
  await page.getByRole("button", { name: /更喜欢这部/ }).first().click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await page.getByRole("button", { name: "撤销上次" }).click();
  await expect(page.getByText(/本次已完成/)).toContainText("0");
  await expect(page.locator(".media-card h2").nth(0)).toHaveText(originalPair[0]);
  await expect(page.locator(".media-card h2").nth(1)).toHaveText(originalPair[1]);
  await page.getByRole("button", { name: /更喜欢这部/ }).first().click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await page.getByRole("button", { name: "查看当前结果" }).click();
  await expect(page.getByRole("heading", { name: "你的偏好序列" })).toBeVisible();
  await expect(page.getByText("不确定性较初始降低")).toBeVisible();
  await expect(page.getByText("用于本次排序的人工比较")).toBeVisible();
  await expect(page.getByText(/当前平均值 .*越低越稳定/)).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(16);
  await page.getByRole("button", { name: /两两比较/ }).click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await page.getByRole("button", { name: /备份与导出/ }).click();
  await expect(page.getByRole("button", { name: /下载 JSON 备份/ })).toBeVisible();
});
