import { expect, test } from "@playwright/test";

test("demo project can compare, resume, and show ranked results", async ({ page }) => {
  await page.goto("/");
  await page.locator("html[data-resorter-ready='true']").waitFor();
  await page.getByRole("button", { name: "先用演示数据体验" }).click();
  await expect(page.getByRole("heading", { name: /demo 的已评分收藏/ })).toBeVisible();
  await expect(page.getByText(/后验信息增益选择相邻作品/)).toBeVisible();
  await expect(page.getByText(/每次回答后动态重估剩余区间/)).toBeVisible();
  await expect(page.locator("#distribution-preset option")).toHaveText(["均匀 1–10", "保持原分布", "高分辨率尾部", "反 J 分布", "自定义权重"]);
  await expect(page.locator("#distribution-preset")).toHaveValue("high-tail");
  await page.locator("#distribution-preset").selectOption("reverse-j");
  await expect(page.getByText(/约 50% 为 1 分/)).toBeVisible();
  await page.getByRole("button", { name: /开始快速比较 · 动态停止/ }).click();
  await expect(page.getByRole("heading", { name: "哪一部在你的偏好中更靠前？" })).toBeVisible();
  await expect(page.getByText(/原评分 \d/)).toHaveCount(0);
  const originalPair = await page.locator(".media-card h2").allTextContents();
  await page.getByRole("button", { name: /更喜欢这部/ }).first().click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await expect(page.getByText("动态剩余预测")).toBeVisible();
  await expect(page.getByText(/\d+\/64 · \d+%（90% MC/).first()).toBeVisible();
  await expect(page.getByText(/全局分桶风险/)).toBeVisible();
  await expect(page.getByText(/全局分桶可信度/)).toBeVisible();
  await expect(page.getByText(/\/ 参考/)).toHaveCount(0);
  await page.getByRole("button", { name: "撤销上次" }).click();
  await expect(page.getByText(/本次已完成/)).toContainText("0");
  await expect(page.locator(".media-card h2").nth(0)).toHaveText(originalPair[0]);
  await expect(page.locator(".media-card h2").nth(1)).toHaveText(originalPair[1]);
  await page.getByRole("button", { name: /更喜欢这部/ }).first().click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await page.getByRole("button", { name: "查看当前结果" }).click();
  await expect(page.getByRole("heading", { name: "你的偏好序列" })).toBeVisible();
  await expect(page.locator("#result-distribution-preset")).toHaveValue("reverse-j");
  await expect(page.getByText("全局分桶可信度")).toBeVisible();
  await expect(page.getByText(/停止要求 90% MC 下界达到 90%/)).toBeVisible();
  await expect(page.getByText(/全表预期跨桶/)).toBeVisible();
  await expect(page.getByText(/概率仅代表模型内近似/)).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(16);
  await expect(page.locator("#stopping-target")).toHaveCount(0);
  await page.locator("#result-distribution-preset").selectOption("uniform");
  await expect(page.locator("#result-distribution-preset")).toHaveValue("uniform");
  await page.getByRole("button", { name: /两两比较/ }).click();
  await expect(page.getByText(/本次已完成/)).toContainText("1");
  await page.getByRole("button", { name: /备份与导出/ }).click();
  await expect(page.getByRole("button", { name: /下载 JSON 备份/ })).toBeVisible();
});
